// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelApi.Models;

#nullable disable

namespace TravelApi.Migrations
{
    [DbContext(typeof(TravelApiContext))]
    [Migration("20230606210445_AddInitial")]
    partial class AddInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TravelApi.Models.Destination", b =>
                {
                    b.Property<int>("DestinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("DestinationId");

                    b.ToTable("Destinations");

                    b.HasData(
                        new
                        {
                            DestinationId = 1,
                            City = "Portland",
                            Country = "USA",
                            Description = "A programming school",
                            Name = "Epicodus"
                        },
                        new
                        {
                            DestinationId = 2,
                            City = "Portland",
                            Country = "USA",
                            Description = "City center",
                            Name = "Pioneer Square"
                        },
                        new
                        {
                            DestinationId = 3,
                            City = "Portland",
                            Country = "USA",
                            Description = "City Park",
                            Name = "Council Crest"
                        },
                        new
                        {
                            DestinationId = 4,
                            City = "Tokyo",
                            Country = "Japan",
                            Description = "Pedestrian Scramble",
                            Name = "Shibuya Crossing"
                        },
                        new
                        {
                            DestinationId = 5,
                            City = "Tokyo",
                            Country = "Japan",
                            Description = "Lookout Point",
                            Name = "Tokyo Tower"
                        });
                });

            modelBuilder.Entity("TravelApi.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            Date = new DateTime(2023, 6, 6, 14, 4, 45, 581, DateTimeKind.Local).AddTicks(9110),
                            DestinationId = 1,
                            Message = "Cool spot!",
                            Rating = 5,
                            UserId = 2
                        },
                        new
                        {
                            ReviewId = 2,
                            Date = new DateTime(2023, 6, 6, 14, 4, 45, 581, DateTimeKind.Local).AddTicks(9150),
                            DestinationId = 4,
                            Message = "Very Busy Place!",
                            Rating = 7,
                            UserId = 3
                        },
                        new
                        {
                            ReviewId = 3,
                            Date = new DateTime(2023, 6, 6, 14, 4, 45, 581, DateTimeKind.Local).AddTicks(9150),
                            DestinationId = 3,
                            Message = "Woah nice views!",
                            Rating = 10,
                            UserId = 2
                        },
                        new
                        {
                            ReviewId = 4,
                            Date = new DateTime(2023, 6, 6, 14, 4, 45, 581, DateTimeKind.Local).AddTicks(9150),
                            DestinationId = 1,
                            Message = "A good place to learn how to program",
                            Rating = 6,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("TravelApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Name = "Kymani"
                        },
                        new
                        {
                            UserId = 2,
                            Name = "Qayden"
                        },
                        new
                        {
                            UserId = 3,
                            Name = "Renee"
                        });
                });

            modelBuilder.Entity("TravelApi.Models.Review", b =>
                {
                    b.HasOne("TravelApi.Models.Destination", "Destination")
                        .WithMany("Reviews")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelApi.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Destination");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TravelApi.Models.Destination", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("TravelApi.Models.User", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
